[phases.setup]
nixPkgs = ['...', 'bun']   # "..." keeps nodejs & yarn that Nixpacks injected

[phases.install]
work_dir = 'apps/web'
cmds = ['bun install --frozen-lockfile']

[phases.build]
work_dir = 'apps/web'
cmds = ['bun run build']

[start]
work_dir = 'apps/web'
cmd = 'bun run --cwd apps/web start'
