services:
  ai-audio-books-db:
    image: pgvector/pgvector:pg16
    restart: on-failure
    container_name: ai-audio-books-db
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    volumes:
      - db-data:/var/lib/postgresql/data
  rabbit:
    image: rabbitmq
    ports:
      - "5672:5672"
  redis:
    image: redis
    ports:
      - "6379:6379"
volumes:
  db-data:
