services:
  ai-audio-books-db:
    image: pgvector/pgvector:pg16
    restart: on-failure
    container_name: ai-audio-books-db
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    volumes:
      - db-data:/var/lib/postgresql/data
  rabbit:
    image: rabbitmq:4.1-management
    ports:
      - "5672:5672"
      - "15672:15672" # optional: management UI at http://localhost:15672
    environment:
      RABBITMQ_DEFAULT_USER: worker
      RABBITMQ_DEFAULT_PASS: worker
      RABBITMQ_DEFAULT_VHOST: /

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
volumes:
  db-data:
