name: Pre Deploy to Railway

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Bun
        uses: oven-sh/setup-bun@v2
        with:
          bun-version: 1.2.0

      - name: Run Migrations
        run: npx prisma migrate deploy
        working-directory: ./packages/database
        env:
          DATABASE_URL: ${{ secrets.DATABASE_URL }}

      - name: Install Railway
        run: yarn global add @railway/cli

      - name: Deploy Repository
        run: |
          railway up -d -s "ai-audio-books"
        env:
          RAILWAY_TOKEN: ${{ secrets.RAILWAY_TOKEN }}
